{"name":"error_tools","vers":"0.1.3","deps":[{"name":"anyhow","req":"~1.0","features":[],"optional":true,"default_features":true,"target":null,"kind":"normal"},{"name":"test_tools","req":"~0.1","features":[],"optional":false,"default_features":true,"target":null,"kind":"dev"},{"name":"thiserror","req":"~1.0","features":[],"optional":true,"default_features":true,"target":null,"kind":"normal"}],"cksum":"5d76564d4af0d794da9ae1d024e07c3c27dd88677150896307da21b345d24234","features":{"default":["use_std","error_handling_for_lib","error_handling_for_app"],"error_handling_for_app":["anyhow"],"error_handling_for_lib":["thiserror"],"full":["use_std","error_handling_for_lib","error_handling_for_app"],"use_alloc":[],"use_std":[]},"yanked":false}